In [8]:
# import library
import pandas as pd

In [9]:
# import data 
df = pd.read_csv("students_data.csv")

In [10]:
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD

In [11]:
# find the duplicates
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
dtype: bool

In [12]:
# remove the duplicates
df.drop_duplicates()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [ ]:
# find the null values
df.isnull().sum()

student_id        0
name              0
age               3
gender            0
grade             0
math_score       18
english_score     8
science_score     0
enrolled_date     0
remarks           0
dtype: int64

In [ ]:
df['name'].str.lower().str.title()

0        Jane Smith
1          John Doe
2          Chris P.
3        Jane Smith
4       Sara O'Neil
5     Mike O’Reilly
6          Ali Khan
7       Sara O'Neil
8     Mike O’Reilly
9      Robert Brown
10        Lucy Gray
11     Simran Singh
12         Patel R.
13         Patel R.
14         Ali Khan
15        Lucy Gray
16         Chris P.
17         Ali Khan
18     Simran Singh
19         Patel R.
20      Sara O'Neil
21         John Doe
22      Sara O'Neil
23       Jane Smith
24         John Doe
25    Mike O’Reilly
26         John Doe
27     Simran Singh
28      Sara O'Neil
29         Patel R.
30         Patel R.
Name: name, dtype: str

In [ ]:
df.loc[:,'name'] = df['name'].str.lower().str.title()

In [ ]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,NaN,64,83,2022/06/11,Average

In [ ]:
df['age']

0     16.0
1     16.0
2      NaN
3     16.0
4     16.0
5     16.0
6     17.0
7     17.0
8     16.0
9     17.0
10    17.0
11    16.0
12    17.0
13    17.0
14    17.0
15    16.0
16     NaN
17    18.0
18    17.0
19    17.0
20    17.0
21    18.0
22    17.0
23    17.0
24    18.0
25    17.0
26     NaN
27    16.0
28    17.0
29    17.0
30    17.0
Name: age, dtype: float64

In [ ]:
df['age'].unique()

array([16., nan, 17., 18.])

In [ ]:
age_mean = df['age'].mean().round(0)
age_mean

np.float64(17.0)

In [ ]:
df['age'] = df['age'].fillna(age_mean)

In [ ]:
df['age'].isnull().sum()

np.int64(0)

In [ ]:
df['gender'].str.lower().str.title()

0     Female
1       Male
2       Male
3     Female
4       Male
5     Female
6     Female
7     Female
8     Female
9     Female
10      Male
11    Female
12    Female
13      Male
14      Male
15    Female
16    Female
17      Male
18      Male
19      Male
20      Male
21    Female
22      Male
23    Female
24      Male
25      Male
26      Male
27    Female
28    Female
29      Male
30      Male
Name: gender, dtype: str

In [ ]:
df.loc[:,'gender'] = df['gender'].str.lower().str.title()

In [ ]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,Female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10th,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,Male,10,NaN,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,Female,10,NaN,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,Male,11,NaN,96,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,NaN,NaN,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,Female,11,64.0,NaN,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,Female,12,NaN,63,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,missing,89,06/12/2022,poor
9,109,Robert Brown,17.0,Female,12,NaN,missing,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,Male,11th,65.0,67,100,06/12/2022,excellent
11,111,Simran Singh,16.0,Female,11th,NaN,missing,95,2022-06-10,average
12,112,Patel R.,17.0,Female,11,NaN,87,89,2022-06-10,poor
13,113,Patel R.,17.0,Male,10,NaN,NaN,98,06/12/2022,Average
14,114,Ali Khan,17.0,Male,12,NaN,91,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,NaN,NaN,72,2022/06/11,excellent
17,117,Ali Khan,18.0,Male,11th,67.0,74,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74,62,2022/06/11,average
19,119,Patel R.,17.0,Male,11th,73.0,NaN,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,NaN,missing,89,2022-06-10,average
21,121,John Doe,18.0,Female,11,66.0,72,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,Male,11th,75.0,NaN,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11th,NaN,missing,63,06/12/2022,excellent
24,124,John Doe,18.0,Male,11th,NaN,NaN,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10th,64.0,missing,67,06/12/2022,good student
27,127,Simran Singh,16.0,Female,12,NaN,76,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,Female,11,NaN,64,89,2022-06-10,average
29,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average
30,129,Patel R.,17.0,Male,11,NaN,64,83,2022/06/11,Average

In [14]:
df['grade'].isnull().sum()

np.int64(0)

In [23]:
df['grade'].unique()

<StringArray>
['11', '10th', '10', '12', '11th']
Length: 5, dtype: str

In [27]:
df['grade'] = df['grade'].replace({'10th':'10','11th':'11'})

In [33]:
df['grade'].unique

<bound method Series.unique of 0     11
1     10
2     10
3     10
4     11
5     10
6     11
7     12
8     12
9     12
10    11
11    11
12    11
13    10
14    12
15    12
16    11
17    11
18    10
19    11
20    10
21    11
22    11
23    11
24    11
25    12
26    10
27    12
28    11
29    11
30    11
Name: grade, dtype: str>

In [43]:
df['math_score'].isnull().sum()

np.int64(0)

In [ ]:
math = df['math_score'].mean()
math

np.float64(74.0)

In [40]:
df['math_score'] = df['math_score'].fillna(math)

In [45]:
df.head()

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,NaN,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,74.0,missing,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,74.0,missing,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,74.0,96,64,2022-06-10,GOOD

In [47]:
df['english_score'].isnull().sum()

np.int64(8)

In [48]:
df['english_score'].unique()

<StringArray>
[      nan,      '95', 'missing',      '96',      '63',      '67',      '87',
      '91',      '74',      '72',      '80',      '76',      '64']
Length: 13, dtype: str

In [52]:
df['english_score'].dtype

In [56]:
df['english_score'] = pd.to_numeric(df['english_score'],errors='coerce')

In [57]:
df['english_score'].dtype

dtype('float64')

In [67]:
english = df['english_score'].mean().round(0)

In [ ]:
df['english_score'] = df['english_score'].fillna(english)

In [71]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,77.0,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95.0,94,10-06-2022,GOOD
2,102,Chris P.,NaN,MALE,10,74.0,77.0,69,06/12/2022,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,74.0,77.0,62,10-06-2022,average
4,104,Sara O'Neil,16.0,male,11,74.0,96.0,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,74.0,77.0,83,06/12/2022,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,77.0,75,06/12/2022,Good
7,107,Sara O'Neil,17.0,female,12,74.0,63.0,62,2022/06/11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,77.0,89,06/12/2022,poor
9,109,Robert Brown,17.0,female,12,74.0,77.0,97,10-06-2022,needs improvement
10,110,Lucy Gray,17.0,male,11,65.0,67.0,100,06/12/2022,excellent
11,111,Simran Singh,16.0,FEMALE,11,74.0,77.0,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,74.0,87.0,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,74.0,77.0,98,06/12/2022,Average
14,114,Ali Khan,17.0,male,12,74.0,91.0,67,2022/06/11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91.0,94,06/12/2022,Average
16,116,Chris P.,NaN,Female,11,74.0,77.0,72,2022/06/11,excellent
17,117,Ali Khan,18.0,male,11,67.0,74.0,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74.0,62,2022/06/11,average
19,119,Patel R.,17.0,MALE,11,73.0,77.0,90,06/12/2022,Good
20,120,Sara O'Neil,17.0,Male,10,74.0,77.0,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72.0,94,10-06-2022,Average
22,122,Sara O'Neil,17.0,MALE,11,75.0,77.0,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11,74.0,77.0,63,06/12/2022,excellent
24,124,John Doe,18.0,MALE,11,74.0,77.0,91,06/12/2022,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80.0,63,10-06-2022,Average
26,126,John Doe,NaN,Male,10,64.0,77.0,67,06/12/2022,good student
27,127,Simran Singh,16.0,FEMALE,12,74.0,76.0,80,06/12/2022,poor
28,128,Sara O'Neil,17.0,female,11,74.0,64.0,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,74.0,64.0,83,2022/06/11,Average
30,129,Patel R.,17.0,male,11,74.0,64.0,83,2022/06/11,Average

In [78]:
df['enrolled_date'].unique()

<StringArray>
['2022-06-10', '10-06-2022', '06/12/2022', '2022/06/11']
Length: 4, dtype: str

In [79]:
dict_date = {
    '10-06-2022':'2022-06-10',
    '06/12/2022':'2022-06-12',
    '2022/06/11':'2022-06-11'
}

In [80]:
df['enrolled_date'] = df['enrolled_date'].replace(dict_date)

In [81]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,77.0,66,2022-06-10,excellent
1,101,John Doe,16.0,Male,10,74.0,95.0,94,2022-06-10,GOOD
2,102,Chris P.,NaN,MALE,10,74.0,77.0,69,2022-06-12,needs improvement
3,103,Jane Smith,16.0,FEMALE,10,74.0,77.0,62,2022-06-10,average
4,104,Sara O'Neil,16.0,male,11,74.0,96.0,64,2022-06-10,GOOD
5,105,Mike O’Reilly,16.0,Female,10,74.0,77.0,83,2022-06-12,needs improvement
6,106,Ali Khan,17.0,female,11,64.0,77.0,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,74.0,63.0,62,2022-06-11,excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,77.0,89,2022-06-12,poor
9,109,Robert Brown,17.0,female,12,74.0,77.0,97,2022-06-10,needs improvement
10,110,Lucy Gray,17.0,male,11,65.0,67.0,100,2022-06-12,excellent
11,111,Simran Singh,16.0,FEMALE,11,74.0,77.0,95,2022-06-10,average
12,112,Patel R.,17.0,female,11,74.0,87.0,89,2022-06-10,poor
13,113,Patel R.,17.0,male,10,74.0,77.0,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,74.0,91.0,67,2022-06-11,poor
15,115,Lucy Gray,16.0,Female,12,65.0,91.0,94,2022-06-12,Average
16,116,Chris P.,NaN,Female,11,74.0,77.0,72,2022-06-11,excellent
17,117,Ali Khan,18.0,male,11,67.0,74.0,81,2022-06-10,GOOD
18,118,Simran Singh,17.0,Male,10,100.0,74.0,62,2022-06-11,average
19,119,Patel R.,17.0,MALE,11,73.0,77.0,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,74.0,77.0,89,2022-06-10,average
21,121,John Doe,18.0,female,11,66.0,72.0,94,2022-06-10,Average
22,122,Sara O'Neil,17.0,MALE,11,75.0,77.0,66,2022-06-10,good student
23,123,Jane Smith,17.0,Female,11,74.0,77.0,63,2022-06-12,excellent
24,124,John Doe,18.0,MALE,11,74.0,77.0,91,2022-06-12,GOOD
25,125,Mike O’Reilly,17.0,Male,12,94.0,80.0,63,2022-06-10,Average
26,126,John Doe,NaN,Male,10,64.0,77.0,67,2022-06-12,good student
27,127,Simran Singh,16.0,FEMALE,12,74.0,76.0,80,2022-06-12,poor
28,128,Sara O'Neil,17.0,female,11,74.0,64.0,89,2022-06-10,average
29,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average
30,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average

In [ ]:
df['remarks'].unique

<StringArray>
[        'excellent',              'GOOD', 'needs improvement',
           'average',              'Good',              'poor',
           'Average',      'good student']
Length: 8, dtype: str

In [91]:
df['remarks'] = df['remarks'].str.lower().str.title()

In [92]:
df

,student_id,name,age,gender,grade,math_score,english_score,science_score,enrolled_date,remarks
0,100,Jane Smith,16.0,female,11,75.0,77.0,66,2022-06-10,Excellent
1,101,John Doe,16.0,Male,10,74.0,95.0,94,2022-06-10,Good
2,102,Chris P.,NaN,MALE,10,74.0,77.0,69,2022-06-12,Needs Improvement
3,103,Jane Smith,16.0,FEMALE,10,74.0,77.0,62,2022-06-10,Average
4,104,Sara O'Neil,16.0,male,11,74.0,96.0,64,2022-06-10,Good
5,105,Mike O’Reilly,16.0,Female,10,74.0,77.0,83,2022-06-12,Needs Improvement
6,106,Ali Khan,17.0,female,11,64.0,77.0,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,74.0,63.0,62,2022-06-11,Excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,77.0,89,2022-06-12,Poor
9,109,Robert Brown,17.0,female,12,74.0,77.0,97,2022-06-10,Needs Improvement
10,110,Lucy Gray,17.0,male,11,65.0,67.0,100,2022-06-12,Excellent
11,111,Simran Singh,16.0,FEMALE,11,74.0,77.0,95,2022-06-10,Average
12,112,Patel R.,17.0,female,11,74.0,87.0,89,2022-06-10,Poor
13,113,Patel R.,17.0,male,10,74.0,77.0,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,74.0,91.0,67,2022-06-11,Poor
15,115,Lucy Gray,16.0,Female,12,65.0,91.0,94,2022-06-12,Average
16,116,Chris P.,NaN,Female,11,74.0,77.0,72,2022-06-11,Excellent
17,117,Ali Khan,18.0,male,11,67.0,74.0,81,2022-06-10,Good
18,118,Simran Singh,17.0,Male,10,100.0,74.0,62,2022-06-11,Average
19,119,Patel R.,17.0,MALE,11,73.0,77.0,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,74.0,77.0,89,2022-06-10,Average
21,121,John Doe,18.0,female,11,66.0,72.0,94,2022-06-10,Average
22,122,Sara O'Neil,17.0,MALE,11,75.0,77.0,66,2022-06-10,Good Student
23,123,Jane Smith,17.0,Female,11,74.0,77.0,63,2022-06-12,Excellent
24,124,John Doe,18.0,MALE,11,74.0,77.0,91,2022-06-12,Good
25,125,Mike O’Reilly,17.0,Male,12,94.0,80.0,63,2022-06-10,Average
26,126,John Doe,NaN,Male,10,64.0,77.0,67,2022-06-12,Good Student
27,127,Simran Singh,16.0,FEMALE,12,74.0,76.0,80,2022-06-12,Poor
28,128,Sara O'Neil,17.0,female,11,74.0,64.0,89,2022-06-10,Average
29,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average
30,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average

In [101]:
# change the columns name with titel
df.columns = df.columns.str.lower().str.title()

In [102]:
df

,Student_Id,Name,Age,Gender,Grade,Math_Score,English_Score,Science_Score,Enrolled_Date,Remarks
0,100,Jane Smith,16.0,female,11,75.0,77.0,66,2022-06-10,Excellent
1,101,John Doe,16.0,Male,10,74.0,95.0,94,2022-06-10,Good
2,102,Chris P.,NaN,MALE,10,74.0,77.0,69,2022-06-12,Needs Improvement
3,103,Jane Smith,16.0,FEMALE,10,74.0,77.0,62,2022-06-10,Average
4,104,Sara O'Neil,16.0,male,11,74.0,96.0,64,2022-06-10,Good
5,105,Mike O’Reilly,16.0,Female,10,74.0,77.0,83,2022-06-12,Needs Improvement
6,106,Ali Khan,17.0,female,11,64.0,77.0,75,2022-06-12,Good
7,107,Sara O'Neil,17.0,female,12,74.0,63.0,62,2022-06-11,Excellent
8,108,Mike O’Reilly,16.0,Female,12,80.0,77.0,89,2022-06-12,Poor
9,109,Robert Brown,17.0,female,12,74.0,77.0,97,2022-06-10,Needs Improvement
10,110,Lucy Gray,17.0,male,11,65.0,67.0,100,2022-06-12,Excellent
11,111,Simran Singh,16.0,FEMALE,11,74.0,77.0,95,2022-06-10,Average
12,112,Patel R.,17.0,female,11,74.0,87.0,89,2022-06-10,Poor
13,113,Patel R.,17.0,male,10,74.0,77.0,98,2022-06-12,Average
14,114,Ali Khan,17.0,male,12,74.0,91.0,67,2022-06-11,Poor
15,115,Lucy Gray,16.0,Female,12,65.0,91.0,94,2022-06-12,Average
16,116,Chris P.,NaN,Female,11,74.0,77.0,72,2022-06-11,Excellent
17,117,Ali Khan,18.0,male,11,67.0,74.0,81,2022-06-10,Good
18,118,Simran Singh,17.0,Male,10,100.0,74.0,62,2022-06-11,Average
19,119,Patel R.,17.0,MALE,11,73.0,77.0,90,2022-06-12,Good
20,120,Sara O'Neil,17.0,Male,10,74.0,77.0,89,2022-06-10,Average
21,121,John Doe,18.0,female,11,66.0,72.0,94,2022-06-10,Average
22,122,Sara O'Neil,17.0,MALE,11,75.0,77.0,66,2022-06-10,Good Student
23,123,Jane Smith,17.0,Female,11,74.0,77.0,63,2022-06-12,Excellent
24,124,John Doe,18.0,MALE,11,74.0,77.0,91,2022-06-12,Good
25,125,Mike O’Reilly,17.0,Male,12,94.0,80.0,63,2022-06-10,Average
26,126,John Doe,NaN,Male,10,64.0,77.0,67,2022-06-12,Good Student
27,127,Simran Singh,16.0,FEMALE,12,74.0,76.0,80,2022-06-12,Poor
28,128,Sara O'Neil,17.0,female,11,74.0,64.0,89,2022-06-10,Average
29,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average
30,129,Patel R.,17.0,male,11,74.0,64.0,83,2022-06-11,Average